---
title: "Group 48 CA pollution burden"
author: "Kiera Matiska and Shuying Yu"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach Packages
library(tidyverse)
library(here)
library(janitor)
library(hexbin)
```

## Read in and tidy the data

- Use the `read_csv()` and the `here` package to read in ces3demographics.csv
- Use `clean_names()` from the `janitor` package to rename column headers to lower-snake case

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```


## Create scatter plot

Create a hex plot with variables proportion white (`white_percent`) on the x-axis and CalEnviroScreen 3.0 score (`ces_3_0_score`) on the y-axis

```{r}
# Scatterplot
ggplot(data = ces, aes(x = white_percent,
                       y = ces_3_0_score)) +
  geom_hex() + # Define hex
  labs(title = "Environmental Health Score of Different Areas by Percentage of White People", # Add title
       x = "White Person Percentage (%)", # Add x-axis label
       y = "Environmental Health Score") # Add y-axis label
```

